In [8]:
#import libraries
import numpy as np
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

## Question 1:
**Component-wise division v/u**

In [9]:
#use numpy to create vector v and u
v = np.array([2,4,6,8,10])
u = np.array([1,3,5,7,9])

In [10]:
#divide vector v by vector u
v/u

array([2.        , 1.33333333, 1.2       , 1.14285714, 1.11111111])

## Question 1(ii):
**Compute 3v − 2u + 0.5v**

In [11]:
#compute the second operation
(3*v) - (2*u) + (0.5*v)

array([ 5.,  8., 11., 14., 17.])

## Question 1b:
**Compute the Euclidean norm (magnitude) of the vector v = [8, 0, 5, 2, 1]**

In [13]:
#use numpy to create vector v
v = np.array([8, 0, 5, 2, 1])

In [15]:
# Compute the Euclidean magnitude
euclidean_norm = np.linalg.norm(v)
euclidean_norm

9.695359714832659

## Question 2:
**Compute the determinant of a matrix A**

In [16]:
#use numpy to create matrix A

A = np.array([[2, 3, 7],
              [-4, 0, 6],
              [1, 5, 0]])

In [18]:
# Compute the determinant
determinant = np.linalg.det(A)
determinant

-181.99999999999997

## Question 3:
**Compute the eigenvalues and eigenvectors of matrix B.**

In [19]:
#use numpy to create matrix B
B = np.array([[3, 2, 4],
              [2, 0, 2],
              [4, 2, 3]])

In [24]:
# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(B)

# Output the results
print("Eigenvalues of the matrix B are: \n", eigenvalues)
print("\nEigenvectors of the matrix B are:\n", eigenvectors)

Eigenvalues of the matrix B are: 
 [-1.  8. -1.]

Eigenvectors of the matrix B are:
 [[-0.74535599  0.66666667 -0.21539222]
 [ 0.2981424   0.33333333 -0.77010996]
 [ 0.59628479  0.66666667  0.6004472 ]]


## Question 3:
**Verify whether the following vectors are eigenvectors of the matrix D**

In [27]:
#use numpy to create matrix D
D = np.array([[3, 1, 2],
              [1, 3, 1],
              [2, 1, 3]])

#compute vector v1 and v2
v1 = np.array([1, 1, 1])
v2 = np.array([-1, 1, -1])

In [29]:
# Compute D * v1 and D * v2
Dv1 = np.dot(D, v1)
Dv2 = np.dot(D, v2)

print("D * v1 =", Dv1)
print("D * v2 =", Dv2)

D * v1 = [6 5 6]
D * v2 = [-4  1 -4]


In [30]:
# Check if D * v1 is a scalar multiple of v1
if np.allclose(Dv1, v1 * (Dv1[0] / v1[0])):
    print("v1 is an eigenvector of D with eigenvalue", Dv1[0] / v1[0])
else:
    print("v1 is not an eigenvector of D")

# Check if D * v2 is a scalar multiple of v2
if np.allclose(Dv2, v2 * (Dv2[0] / v2[0])):
    print("v2 is an eigenvector of D with eigenvalue", Dv2[0] / v2[0])
else:
    print("v2 is not an eigenvector of D")

v1 is not an eigenvector of D
v2 is not an eigenvector of D


## Question 4:
**Perform PCA on a dataset to reduce the dimensionality of the dataset to two dimensions.**

In [31]:
#use numpy to create the dataset
X = np.array([[4, 2, 3],
              [3, 13, 4],
              [9, 4, 5],
              [0, 5, 7]])

### Step 1 - Standardization

In [ ]:
# Step 1: Standardize the dataset
scaler = StandardScaler(with_std=False)
X_standardized = scaler.fit_transform(X)

# Calculate the standard deviations for scaling
std_devs = np.std(X_standardized, axis=0)
X_standardized = X_standardized / std_devs

### Step 2 - Covariance Matrix Computation

In [32]:
# Step 2: Compute the covariance matrix
n = X_standardized.shape[0]
cov_matrix = np.dot(X_standardized.T, X_standardized) / n

### Step 3 - Compute Eigenvectors and Eigenvalues

In [33]:
# Step 3: Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


Eigenvalues:
 [0.54397045 1.41900369 1.03702586]

Eigenvectors:
 [[-0.69154646 -0.72136936  0.03727924]
 [-0.41590627  0.35545374 -0.83706309]
 [-0.59058062  0.59437268  0.54583482]]


### Step 4 - Create Feature Vector

In [34]:
# Step 4: Sort the eigenvalues and corresponding eigenvectors
sorted_indices = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

print("\nSorted eigenvalues:\n", sorted_eigenvalues)


Sorted eigenvalues:
 [1.41900369 1.03702586 0.54397045]

Top 2 eigenvectors:
 [[-0.72136936  0.03727924]
 [ 0.35545374 -0.83706309]
 [ 0.59437268  0.54583482]]


In [37]:
# Choose the top 2 eigenvectors
top_2_eigenvectors = sorted_eigenvectors[:, :2]

print("\nTop 2 eigenvectors:\n", top_2_eigenvectors)


Top 2 eigenvectors:
 [[-0.72136936  0.03727924]
 [ 0.35545374 -0.83706309]
 [ 0.59437268  0.54583482]]


### Step 5: Recast the Data Along the Principal Components Axes

In [38]:
# Step 6: Transform the original dataset
X_reduced = np.dot(X_standardized, top_2_eigenvectors)

print("\nReduced dataset:\n", X_reduced)


Reduced dataset:
 [[-1.04315003  0.15454493]
 [ 0.51600533 -1.68896784]
 [-1.18256916  0.54997873]
 [ 1.70971385  0.98444418]]


# Question 4b
**Compute the percentage of variance explained by each principal component**

In [40]:
explained_variance = sorted_eigenvalues / np.sum(sorted_eigenvalues) * 100

# Output the results
print("Standardized dataset:\n", X_standardized)
print("\nCovariance matrix:\n", cov_matrix)



print("\nPercentage of variance explained by each principal component:\n", explained_variance)

Standardized dataset:
 [[ 0.         -0.95618289 -1.18321596]
 [-0.3086067   1.67332005 -0.50709255]
 [ 1.5430335  -0.47809144  0.16903085]
 [-1.2344268  -0.23904572  1.52127766]]

Covariance matrix:
 [[ 1.         -0.23975611 -0.36514837]
 [-0.23975611  1.         -0.0404061 ]
 [-0.36514837 -0.0404061   1.        ]]

Percentage of variance explained by each principal component:
 [47.30012302 34.56752871 18.13234827]
